language: node_js
node_js:
  - 10
  - 12

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run tsc
  - npm run lint
  - npm run build
  - npm run test:coverage
  - npm run test:e2e

after_success:
  - npm install -g codecov
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
